apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-api
spec:
  template:
    spec:
      containers:
      - env:
        - name: DATABASE_NAME
          valueFrom:
            configMapKeyRef:
              key: DATABASE_NAME
              name: db-connection
        - name: DATABASE_PASSWORD
          valueFrom:
            configMapKeyRef:
              key: DATABASE_PASSWORD
              name: db-connection
        - name: DATABASE_SVC_HOSTNAME
          valueFrom:
            configMapKeyRef:
              key: DATABASE_SVC_HOSTNAME
              name: db-connection
        - name: DATABASE_USER
          valueFrom:
            configMapKeyRef:
              key: DATABASE_USER
              name: db-connection
        name: quarkus
